title: 室内楽演奏会
email: ensemble2018project721@gmail.com
url: "https://Ensemble-Project.github.io/"
description: 2018.07.21 Sat, Bunkyo Civic Hall
theme: 
show_downloads: false
google_analytics: 
gems:
  - jekyll-seo-tag