title: 出張ミニコン
email: ensemble2018project721@gmail.com
url: "https://Ensemble-Project.github.io/"
description: 2019.07.15 Mon, Millennium Hall
theme: 
show_downloads: false
google_analytics: 
gems:
  - jekyll-seo-tag